pipeline:
  name: LMS-CI
  identifier: LMSCI
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: start-mail
        identifier: startmail
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: email
                  identifier: email
                  template:
                    templateRef: Email
                    versionLabel: v1.0
        tags: {}
    - stage:
        name: Build-Stage
        identifier: BuildStage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: ubuntu
                    shell: Sh
                    command: ls
              - step:
                  type: Run
                  name: aws glue
                  identifier: aws_glue
                  spec:
                    connectorRef: account.harnessImage
                    image: amazon/aws-cli
                    shell: Sh
                    command: |-
                      #!/bin/bash
                      # Set your AWS region and Glue job name
                      AWS_REGION="us-east-1"
                      GLUE_JOB_NAME="your-glue-job-name"

                      # Trigger the AWS Glue job
                      job_run_id=$(aws glue start-job-run \
                        --region $AWS_REGION \
                        --job-name $GLUE_JOB_NAME \
                        --query 'JobRunId' \
                        --output text)

                      echo "Started AWS Glue Job: $GLUE_JOB_NAME"
                      echo "Job Run ID: $job_run_id"

                      # Optional: Wait for job completion
                      while true; do
                        job_status=$(aws glue get-job-run \
                          --region $AWS_REGION \
                          --job-name $GLUE_JOB_NAME \
                          --run-id $job_run_id \
                          --query 'JobRun.JobRunState' \
                          --output text)
                          
                        echo "Current Job Status: $job_status"
                        
                        if [[ "$job_status" == "SUCCEEDED" ]]; then
                          echo "Glue Job completed successfully."
                          break
                        elif [[ "$job_status" == "FAILED" || "$job_status" == "TIMEOUT" ]]; then
                          echo "Glue Job failed or timed out."
                          exit 1
                        else
                          sleep 30
                        fi
                      done
                    privileged: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: ipreetgs/Learning-Management-System-Fullstack
        build: <+input>
