pipeline:
  name: LMS
  identifier: LMS
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: email
        identifier: email
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: email
                  identifier: email
                  template:
                    templateRef: Email
                    versionLabel: v1.0
        tags: {}
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: ls
              - step:
                  type: Semgrep
                  name: Semgrep
                  identifier: Semgrep_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: high
                      args:
                        cli: "--config auto --json --upload --exclude-dir node_modules"
                    auth:
                      access_token: 0c72b1d1d91ccdfb5244c7e783ce936fa67c94325bca2cc9ddde6a19f6194d9b
              - parallel:
                  - step:
                      type: Owasp
                      name: Owasp
                      identifier: Owasp_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                  - step:
                      type: OsvScanner
                      name: OsvScanner
                      identifier: OsvScanner_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: learning-management-system-fullstack
        build: <+input>
